-- Insert Avenue Real Estate properties

-- 1. Signature Global Park 2 & 3, Sector 36 Sohna
INSERT INTO properties (title, location, description, price, price_value, type, status, area, area_value, bedrooms, bathrooms, image_url, gallery, features, builder, is_verified, vastu_compliant, latitude, longitude) VALUES
('Signature Global Park 2 & 3', 'Sector 36 Sohna, Haryana', 'Premium affordable housing project by Signature Global offering 2 & 3 BHK apartments. Spread across 17 acres with modern amenities, landscaped gardens, and excellent connectivity to Gurgaon.', '₹45 L onwards', 4500000, 'residential', 'available', '650 - 1200 sq.ft.', 925, 2, 2, 'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800'], ARRAY['Club House', 'Swimming Pool', 'Gym', 'Kids Play Area', '24/7 Security', 'Power Backup', 'Landscaped Gardens'], 'Signature Global', true, true, 28.2385, 77.0567);

-- 2. Signature Global Park 4 & 5, Sector 36 Sohna
INSERT INTO properties (title, location, description, price, price_value, type, status, area, area_value, bedrooms, bathrooms, image_url, features, builder, is_verified, vastu_compliant, latitude, longitude) VALUES
('Signature Global Park 4 & 5', 'Sector 36 Sohna, Haryana', 'Affordable luxury apartments in Sector 36 Sohna by Signature Global. Offers 2 & 3 BHK configurations with excellent specifications. Part of well-planned township.', '₹48 L onwards', 4800000, 'residential', 'available', '700 - 1250 sq.ft.', 975, 2, 2, 'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['Club House', 'Jogging Track', 'Indoor Games', 'Kids Play Area', '24/7 Security', 'Ample Parking'], 'Signature Global', true, true, 28.2392, 77.0574);

-- 3. Central Park Flower Valley, Sector 33 Sohna
INSERT INTO properties (title, location, description, price, price_value, type, status, area, area_value, image_url, features, builder, is_verified, vastu_compliant, latitude, longitude) VALUES
('Central Park Flower Valley', 'Sector 33 Sohna, Haryana', 'Luxury plotted development by Central Park offering premium residential plots. Spread across 150 acres with world-class amenities and a 9-hole golf course.', '₹35 L onwards', 3500000, 'plot', 'available', '180 - 500 sq.yd.', 420, 'https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['Golf Course', 'Club House', 'Swimming Pool', 'Spa', 'Landscaped Gardens', '24/7 Security', 'Gated Community', 'Jogging Track'], 'Central Park', true, true, 28.2356, 77.0521);

-- 4. Signature Global Daxin, Sohna Road
INSERT INTO properties (title, location, description, price, price_value, type, status, area, area_value, image_url, features, builder, is_verified, vastu_compliant, latitude, longitude) VALUES
('Signature Global Daxin', 'Sohna Road, Haryana', 'Commercial and mixed-use development by Signature Global on Sohna Road. Offers retail spaces and office complexes with excellent visibility.', '₹25 L onwards', 2500000, 'commercial', 'available', '300 - 1500 sq.ft.', 900, 'https://images.pexels.com/photos/3945545/pexels-photo-3945545.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['Ample Parking', '24/7 Security', 'Power Backup', 'High Visibility', 'Modern Facade', 'Strategic Location'], 'Signature Global', true, false, 28.2410, 77.0601);

-- 5. Breez Flora Avenue, Sector 33 Sohna
INSERT INTO properties (title, location, description, price, price_value, type, status, area, area_value, bedrooms, bathrooms, image_url, features, builder, is_verified, vastu_compliant, latitude, longitude) VALUES
('Breez Flora Avenue', 'Sector 33 Sohna, Haryana', 'Affordable housing project by Breez Builders offering 2 & 3 BHK apartments. Good connectivity to Sohna city center and Gurgaon.', '₹38 L onwards', 3800000, 'residential', 'available', '600 - 1100 sq.ft.', 850, 2, 2, 'https://images.pexels.com/photos/1029542/pexels-photo-1029542.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['Club House', 'Gym', 'Children Play Area', '24/7 Security', 'Power Backup', 'Landscaped Gardens'], 'Breez Builders', true, true, 28.2348, 77.0515);

-- 6. Trehan Builder Floor, Sector 35 Sohna
INSERT INTO properties (title, location, description, price, price_value, type, status, area, area_value, bedrooms, bathrooms, image_url, features, builder, is_verified, vastu_compliant, latitude, longitude) VALUES
('Trehan Builder Floor', 'Sector 35 Sohna, Haryana', 'Independent builder floors by Trehan Builders offering spacious 3 & 4 BHK units. Independent floors with private terraces and dedicated parking. Low-density living with premium specifications.', '₹55 L onwards', 5500000, 'villa', 'available', '1400 - 2000 sq.ft.', 1700, 3, 3, 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['Private Terrace', 'Modular Kitchen', 'Dedicated Parking', '24/7 Security', 'Power Backup', 'Spa Bathrooms'], 'Trehan Builders', true, true, 28.2420, 77.0612);

-- 7. Shahpuria Developer Builder Floors, Sector 67 Gurgaon
INSERT INTO properties (title, location, description, price, price_value, type, status, area, area_value, bedrooms, bathrooms, image_url, features, builder, is_verified, vastu_compliant, latitude, longitude) VALUES
('Shahpuria Builder Floors Ansal Versalia', 'Sector 67 Gurgaon, Haryana', 'Premium builder floors by Shahpuria Developers in Ansal Versalia, Sector 67. Luxurious 3 & 4 BHK independent floors with modular fittings and modern architecture. Excellent location on Golf Course Extension Road.', '₹85 L onwards', 8500000, 'villa', 'available', '1600 - 2500 sq.ft.', 2050, 3, 3, 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['Private Terrace', 'Modular Kitchen', 'Premium Flooring', 'Dedicated Parking', '24/7 Security', 'Smart Home Features'], 'Shahpuria Developers', true, true, 28.2515, 77.0725);

-- 8. Pitarachaya Dev Luxury Floor, Sector 70 Gurgaon
INSERT INTO properties (title, location, description, price, price_value, type, status, area, area_value, bedrooms, bathrooms, image_url, features, builder, is_verified, vastu_compliant, latitude, longitude) VALUES
('Pitarachaya Dev Luxury Floor', 'Sector 70 Gurgaon, Haryana', 'Ultra-luxury builder floors by Pitarachaya Developers in Sector 70. Premium 4 BHK independent floors with Italian marble, modular kitchen, and smart home automation. Located on Golf Course Extension Road.', '₹1.2 Cr onwards', 12000000, 'villa', 'available', '2200 - 3000 sq.ft.', 2600, 4, 4, 'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['Italian Marble', 'Modular Kitchen', 'Smart Home Automation', 'Private Terrace', 'Dedicated Parking', '24/7 Security', 'Spa Bathroom', 'VRV Air Conditioning'], 'Pitarachaya Developers', true, true, 28.2530, 77.0750);

-- 9. Godrej Nature Plus, Sector 33 Sohna
INSERT INTO properties (title, location, description, price, price_value, type, status, area, area_value, bedrooms, bathrooms, image_url, features, builder, is_verified, vastu_compliant, latitude, longitude) VALUES
('Godrej Nature Plus', 'Sector 33 Sohna, Haryana', 'Premium residential project by Godrej Properties offering 2 & 3 BHK apartments surrounded by nature. Features extensive green cover, sustainable design, and modern amenities from a trusted developer.', '₹52 L onwards', 5200000, 'residential', 'available', '750 - 1300 sq.ft.', 1025, 2, 2, 'https://images.pexels.com/photos/1115804/pexels-photo-1115804.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['Nature Theme', 'Club House', 'Swimming Pool', 'Gym', 'Indoor Games', 'Jogging Track', '24/7 Security', 'Kids Play Area'], 'Godrej Properties', true, true, 28.2365, 77.0535);

-- 10. Signature Global City, Sector 63A Gurgaon
INSERT INTO properties (title, location, description, price, price_value, type, status, area, area_value, bedrooms, bathrooms, image_url, features, builder, is_verified, vastu_compliant, latitude, longitude) VALUES
('Signature Global City', 'Sector 63A Gurgaon, Haryana', 'Strategic affordable housing project by Signature Global on Sohna Road. Offers 2 & 3 BHK apartments with excellent connectivity to Cyber City and Golf Course Extension. RERA registered project.', '₹42 L onwards', 4200000, 'residential', 'available', '600 - 1150 sq.ft.', 875, 2, 2, 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['Club House', 'Gym', 'Swimming Pool', 'Kids Play Area', '24/7 Security', 'Power Backup', 'Jogging Track'], 'Signature Global', true, true, 28.2480, 77.0680);