-- Add more localities/sectors
INSERT INTO localities (name, slug, description, image_url, walkability_score, safety_score, school_rating, avg_price_per_sqft, amenities) VALUES
('Sector 35', 'sector-35-sohna', 'A well-planned residential sector with excellent connectivity to Sohna Road and upcoming infrastructure. Known for affordable builder floors and peaceful environment.', 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800', 75, 82, 4.2, 42000, '{"schools": [{"name": "Delhi Public School", "distance": "4 km"}, {"name": "Ryan International", "distance": "5 km"}], "hospitals": [{"name": "Medanta Hospital", "distance": "8 km"}], "shopping": [{"name": "Omaxe City Centre", "distance": "3 km"}], "transport": [{"name": "Sohna Road", "distance": "2 km"}, {"name": "Proposed Metro Station", "distance": "1.5 km"}]}'),
('Sector 36', 'sector-36-sohna', 'Premium residential sector with luxury high-rise apartments and excellent amenities. Close to major corporate hubs and educational institutions.', 'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=800', 80, 85, 4.5, 55000, '{"schools": [{"name": "GD Goenka School", "distance": "3 km"}, {"name": "Amity International", "distance": "5 km"}], "hospitals": [{"name": "Fortis Hospital", "distance": "6 km"}, {"name": "Artemis Hospital", "distance": "7 km"}], "shopping": [{"name": "MGF Metropolitan Mall", "distance": "8 km"}], "transport": [{"name": "Sohna Road", "distance": "1 km"}, {"name": "NH-48", "distance": "4 km"}]}'),
('Sector 63A', 'sector-63a-gurugram', 'Strategic location on Golf Course Extension Road with premium residential projects and excellent connectivity to Cyber City and Golf Course Road.', 'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=800', 78, 80, 4.3, 65000, '{"schools": [{"name": "Scottish High School", "distance": "2 km"}, {"name": "Lancers International", "distance": "4 km"}], "hospitals": [{"name": "Medanta Hospital", "distance": "5 km"}], "shopping": [{"name": "South Point Mall", "distance": "3 km"}], "transport": [{"name": "Golf Course Extension Road", "distance": "0.5 km"}, {"name": "Rapid Metro", "distance": "6 km"}]}'),
('Sector 67', 'sector-67-gurugram', 'Emerging residential destination with affordable luxury options. Features wide roads, parks, and proximity to Southern Peripheral Road.', 'https://images.pexels.com/photos/1115803/pexels-photo-1115803.jpeg?auto=compress&cs=tinysrgb&w=800', 72, 78, 4.0, 52000, '{"schools": [{"name": "DPS Sector 45", "distance": "4 km"}, {"name": "Shiv Nadar School", "distance": "5 km"}], "hospitals": [{"name": "Columbia Asia", "distance": "6 km"}], "shopping": [{"name": "DLF South Point", "distance": "4 km"}], "transport": [{"name": "Southern Peripheral Road", "distance": "1 km"}, {"name": "NH-48", "distance": "3 km"}]}'),
('Sector 70', 'sector-70-gurugram', 'Premium locality on Southern Peripheral Road with excellent connectivity. Features luxury builder floors and proximity to Sohna Road.', 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=800', 76, 81, 4.4, 58000, '{"schools": [{"name": "Heritage Xperiential School", "distance": "3 km"}, {"name": "Suncity School", "distance": "4 km"}], "hospitals": [{"name": "Fortis Hospital", "distance": "5 km"}], "shopping": [{"name": "Raheja Mall", "distance": "2 km"}], "transport": [{"name": "Sohna Road", "distance": "1 km"}, {"name": "Southern Peripheral Road", "distance": "0.5 km"}]}'),
('Gwal Pahari', 'gwal-pahari', 'Scenic location nestled in the Aravali foothills offering farmhouses and luxury villas. Known for pristine environment and excellent road connectivity.', 'https://images.pexels.com/photos/1520259/pexels-photo-1520259.jpeg?auto=compress&cs=tinysrgb&w=800', 65, 75, 3.8, 85000, '{"schools": [{"name": "Pathways World School", "distance": "5 km"}, {"name": "GD Goenka World School", "distance": "6 km"}], "hospitals": [{"name": "Medanta Hospital", "distance": "12 km"}], "shopping": [{"name": "Artemis Hospital Complex", "distance": "10 km"}], "transport": [{"name": "Gurgaon-Faridabad Road", "distance": "2 km"}, {"name": "Sohna Road", "distance": "5 km"}]}')
ON CONFLICT (slug) DO NOTHING;

-- Add more diverse properties (commercial, plots, villas)
INSERT INTO properties (title, location, description, price, type, status, area, bedrooms, bathrooms, image_url, gallery, features, price_value, area_value, latitude, longitude, address, rera_number, builder, possession_date, is_verified, price_per_sqft, vastu_compliant, facing, age, furnishing, views_count) VALUES
-- Commercial Properties
('M3M Urbana Business Park', 'Sector 67, Gurugram', 'Premium commercial complex with modern office spaces and retail shops. Located on Southern Peripheral Road with excellent visibility from main road. Features high-speed elevators, ample parking, and 24/7 security.', '₹85,00,000', 'commercial', 'available', '1200 sq.ft.', NULL, NULL, 'https://images.pexels.com/photos/323705/pexels-photo-323705.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['https://images.pexels.com/photos/1486322/pexels-photo-1486322.jpeg', 'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg'], ARRAY['Ground + 11 Floors', '3 Side Open Plot', 'Grand Lobby', 'High-Speed Elevators', '100% Power Backup', 'Ample Parking', '24/7 Security', 'Fire Safety Systems', 'CCTV Surveillance', 'AC Common Areas'], 8500000, 1200, 28.4085, 77.0625, 'Tower A, M3M Urbana Business Park, Sector 67, Gurugram', 'HRERA-GGM-572-2021', 'M3M India', '2024-12-31', true, 7083, true, 'East', 'New', 'Raw', 65),

('Vatika Business Centre', 'Sector 83, Gurugram', 'Strategic commercial development on NH-48 with excellent connectivity to Manesar and Delhi. Ideal for offices, showrooms, and retail. Modern amenities with premium finishing.', '₹65,00,000', 'commercial', 'available', '900 sq.ft.', NULL, NULL, 'https://images.pexels.com/photos/260689/pexels-photo-260689.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['https://images.pexels.com/photos/323705/pexels-photo-323705.jpeg', 'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg'], ARRAY['Main Road Facing', 'Corner Unit', 'Large Shop Front', 'High Visibility', 'Power Backup', 'Parking', 'Security', 'Fire Safety'], 6500000, 900, 28.4567, 76.9234, 'Vatika Business Centre, Sector 83, Gurugram', 'HRERA-GGM-345-2020', 'Vatika Group', '2024-06-30', true, 7222, true, 'North', 'New', 'Raw', 48),

-- Plot Properties
('Terra Grand Residential Plots', 'Sector 35, Sohna', 'Premium residential plots in a gated community with wide roads, underground utilities, and landscaped parks. Ideal for building your dream home with complete freedom of design.', '₹45,00,000', 'plot', 'available', '180 sq.yd.', NULL, NULL, 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg', 'https://images.pexels.com/photos/1115803/pexels-photo-1115803.jpeg'], ARRAY['Gated Community', 'Wide Roads (60 ft)', 'Underground Utilities', 'Parks & Green Areas', 'Corner Plots Available', 'Boundary Wall', 'Street Lighting', 'Water Supply', 'Electricity', 'Sewage Lines'], 4500000, 180, 28.2567, 77.0723, 'Terra Grand, Sector 35, Sohna', 'HRERA-SOH-123-2022', 'Terra Group', '2025-03-31', true, 25000, true, 'East', NULL, NULL, 42),

('RPS Savana Plots', 'Sector 88A, Gurugram', 'Well-plotted development on Dwarka Expressway with excellent connectivity to Delhi IGI Airport. Modern infrastructure with club house and sports facilities.', '₹72,00,000', 'plot', 'available', '240 sq.yd.', NULL, NULL, 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg', 'https://images.pexels.com/photos/1520259/pexels-photo-1520259.jpeg'], ARRAY['Dwarka Expressway Facing', 'Club House', 'Swimming Pool', 'Tennis Court', 'Gym', 'Jogging Track', 'Children Play Area', '24/7 Security', 'Gated Community', 'Underground Drainage'], 7200000, 240, 28.5012, 76.8934, 'RPS Savana, Sector 88A, Gurugram', 'HRERA-GGM-789-2021', 'RPS Group', '2024-09-30', true, 30000, true, 'North-East', NULL, NULL, 55),

('Aranya Vihar Plots', 'Sohna Road, Gurugram', 'Premium plotted development near commercial hubs. Features wide roads, green spaces, and excellent connectivity. Affordable luxury plotting in prime location.', '₹38,00,000', 'plot', 'available', '150 sq.yd.', NULL, NULL, 'https://images.pexels.com/photos/53610/large-home-preview-ca.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg', 'https://images.pexels.com/photos/1115803/pexels-photo-1115803.jpeg'], ARRAY['Sohna Road Connectivity', 'Wide Internal Roads', 'Parks', 'Underground Utilities', 'Gated Entry', 'Security', 'Walking Paths', 'Rainwater Harvesting'], 3800000, 150, 28.4234, 77.0412, 'Aranya Vihar, Sohna Road, Gurugram', 'HRERA-GGM-456-2022', 'Ansal API', '2025-06-30', true, 25333, true, 'East', NULL, NULL, 38),

-- Villa Properties
('Whiteland Blisstree Villas', 'Sector 76, Gurugram', 'Luxurious independent villas with private gardens and terraces. Premium Italian marble flooring, modular kitchen, and smart home automation. Gated community with world-class amenities.', '₹2.85 Cr', 'villa', 'available', '4500 sq.ft.', 5, 5, 'https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg', 'https://images.pexels.com/photos/1520259/pexels-photo-1520259.jpeg', 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg'], ARRAY['Private Garden', 'Terrace Garden', 'Italian Marble Flooring', 'Modular Kitchen', 'Smart Home Automation', 'Central AC', 'Private Parking (3 cars)', 'Servant Room', 'Club House Access', 'Pool Access', '24/7 Security', 'Home Theatre Compatible'], 28500000, 4500, 28.4345, 77.0234, 'Whiteland Blisstree, Sector 76, Gurugram', 'HRERA-GGM-234-2022', 'Whiteland Corporation', '2025-12-31', true, 6333, true, 'East', 'New', 'Fully Furnished', 120),

('Eldeco Villa Heights', 'Sector 48, Sohna Road', 'Elegant 4 BHK independent villas with contemporary architecture. Spacious rooms with ample natural light. Premium fittings, landscaped garden, and covered parking.', '₹1.65 Cr', 'villa', 'available', '3200 sq.ft.', 4, 4, 'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg', 'https://images.pexels.com/photos/1486322/pexels-photo-1486322.jpeg'], ARRAY['Independent Villa', 'Landscaped Garden', 'Covered Parking', 'Modular Kitchen', 'Wooden Flooring in Bedrooms', 'POP False Ceiling', 'Branded Sanitary Fittings', 'Power Backup', 'Security System', 'Gated Community'], 16500000, 3200, 28.4765, 77.0345, 'Eldeco Villa Heights, Sector 48, Sohna Road', 'HRERA-GGM-567-2021', 'Eldeco Infrastructure', '2024-06-30', true, 5156, true, 'North', 'New', 'Semi-Furnished', 95),

('Hero Homes Villa Enclave', 'Gwal Pahari', 'Luxury farm villas in the serene Aravali foothills. Sprawling 10000+ sq.ft. built-up area on 1-acre plots. Private pool, landscaped gardens, and 360-degree mountain views.', '₹5.5 Cr', 'villa', 'available', '10500 sq.ft.', 6, 7, 'https://images.pexels.com/photos/1520259/pexels-photo-1520259.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg', 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg', 'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg'], ARRAY['1 Acre Plot', 'Private Pool', 'Infinity Edge Pool', 'Landscaped Gardens', 'Panoramic Aravali Views', 'Home Theatre', 'Gym', 'Spa Room', '6 Car Garage', 'Servant Quarters', 'Borewell', 'Solar Panels', 'Generator Backup', 'CCTV System', 'Gated Entry'], 55000000, 10500, 28.3890, 77.1345, 'Hero Homes Villa Enclave, Gwal Pahari', 'HRERA-FBD-123-2020', 'Hero Realty', NULL, true, 5238, true, 'East', 'New', 'Fully Furnished', 180),

-- More Residential Properties
('Sobha City Towers', 'Sector 108, Gurugram', 'Premium high-rise apartments with golf course views. World-class amenities including clubhouse, swimming pool, and sports facilities. Limited units available.', '₹1.25 Cr', 'residential', 'available', '2100 sq.ft.', 3, 3, 'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg', 'https://images.pexels.com/photos/1486322/pexels-photo-1486322.jpeg'], ARRAY['Golf Course View', 'Club House', 'Swimming Pool', 'Gym', 'Tennis Court', 'Badminton Court', 'Indoor Games', 'Kids Play Area', 'Jogging Track', '24/7 Security', 'Power Backup', 'Basement Parking', 'High-Speed Elevators'], 12500000, 2100, 28.4876, 77.0012, 'Sobha City, Sector 108, Gurugram', 'HRERA-GGM-345-2022', 'Sobha Limited', '2024-12-31', true, 5952, true, 'South-East', 'New', 'Semi-Furnished', 150),

('Mahira Twin Towers', 'Sector 68, Sohna', 'Affordable luxury 2/3 BHK apartments with modern amenities. Strategic location with easy access to Sohna Road and NH-48. Limited inventory available.', '₹55,00,000', 'residential', 'available', '1450 sq.ft.', 3, 2, 'https://images.pexels.com/photos/1115803/pexels-photo-1115803.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg', 'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg'], ARRAY['Club House', 'Gym', 'Swimming Pool', 'Kids Pool', 'Jogging Track', 'Badminton Court', '24/7 Security', 'Power Backup', 'Covered Parking', 'Visitor Parking'], 5500000, 1450, 28.4123, 77.0567, 'Mahira Twin Towers, Sector 68, Sohna', 'HRERA-SOH-567-2022', 'Mahira Creators', '2025-06-30', true, 3793, true, 'North', 'New', 'Raw', 88),

('Puri Emerald Bay', 'Sector 104, Gurugram', 'Premium riverside living with panoramic views of the Nohra river. 4 BHK luxury apartments with Italian marble flooring and German fittings. Resort-style amenities.', '₹1.85 Cr', 'residential', 'available', '2850 sq.ft.', 4, 4, 'https://images.pexels.com/photos/1486322/pexels-photo-1486322.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg', 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg'], ARRAY['Riverside View', 'Italian Marble', 'German Fittings', 'Modular Kitchen', 'Club House', 'Infinity Pool', 'Spa', 'Indoor Games', 'Business Centre', 'Banquet Hall', '24/7 Security', 'Home Automation Ready'], 18500000, 2850, 28.4567, 77.0234, 'Puri Emerald Bay, Sector 104, Gurugram', 'HRERA-GGM-234-2021', 'Puri Constructions', '2024-09-30', true, 6491, true, 'East', 'New', 'Luxury Finish', 145),

('ATS Tourmaline', 'Sector 109, Gurugram', 'Exclusive low-density housing with only 2 apartments per floor. Premium 3.5 BHK with private lobby and servant room. 9-hole golf course access.', '₹2.15 Cr', 'residential', 'coming soon', '2400 sq.ft.', 4, 3, 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg', 'https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg'], ARRAY['Golf Course Access', '2 Apartments/Floor', 'Private Lobby', 'Servant Room', 'Italian Marble', 'Modular Kitchen', 'Club House', 'Swimming Pool', 'Gym', 'Spa', '24/7 Security', 'Basement Parking'], 21500000, 2400, 28.5012, 77.0012, 'ATS Tourmaline, Sector 109, Gurugram', 'HRERA-GGM-567-2023', 'ATS Infrastructure', '2025-12-31', true, 8958, true, 'North-East', 'Under Construction', 'Luxury Finish', 85),

('Paras Tierra', 'Sector 37C, Gurugram', 'Well-connected affordable housing with all modern amenities. 2/3 BHK options with excellent layout and ventilation. RERA approved project.', '₹42,00,000', 'residential', 'available', '1100 sq.ft.', 2, 2, 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['https://images.pexels.com/photos/1115803/pexels-photo-1115803.jpeg', 'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg'], ARRAY['Club House', 'Gym', 'Swimming Pool', 'Kids Play Area', 'Badminton Court', 'Jogging Track', '24/7 Security', 'Power Backup', 'Covered Parking', 'Ample Green Area'], 4200000, 1100, 28.4234, 77.0345, 'Paras Tierra, Sector 37C, Gurugram', 'HRERA-GGM-789-2021', 'Paras Buildtech', NULL, true, 3818, true, 'East', 'New', 'Raw', 72),

('GLS Avenue 51', 'Sector 51, Gurugram', 'Premium 3 BHK apartments in Golf Course Road micro-market. Excellent connectivity to Cyber City and MG Road. High rental yield potential.', '₹1.45 Cr', 'residential', 'available', '1850 sq.ft.', 3, 3, 'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg', 'https://images.pexels.com/photos/1486322/pexels-photo-1486322.jpeg'], ARRAY['Club House', 'Swimming Pool', 'Gym', 'Indoor Games', 'Lawn Tennis', 'Multi-Level Parking', '24/7 Security', 'Power Backup', 'Near Metro', 'Near Schools'], 14500000, 1850, 28.4567, 77.0678, 'GLS Avenue 51, Sector 51, Gurugram', 'HRERA-GGM-123-2020', 'GLS Infratech', '2024-06-30', true, 7837, true, 'South', 'New', 'Semi-Furnished', 110),

('Adani Samsara Ivana', 'Sector 63, Gurugram', 'Ultra-luxury 4 BHK Sky Villas with private pools on every floor. World-class amenities with concierge service. Part of the prestigious Samsara township.', '₹3.25 Cr', 'residential', 'available', '4200 sq.ft.', 4, 5, 'https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=1200', ARRAY['https://images.pexels.com/photos/1520259/pexels-photo-1520259.jpeg', 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg'], ARRAY['Sky Villa', 'Private Pool', 'Italian Marble', 'German Fittings', 'Modular Kitchen', 'Concierge Service', 'Club House', 'Spa', 'Gym', 'Temperature Controlled Pool', 'Private Lift', '6 Car Parking', '24/7 Security'], 32500000, 4200, 28.4234, 77.0678, 'Adani Samsara Ivana, Sector 63, Gurugram', 'HRERA-GGM-345-2022', 'Adani Realty', '2025-12-31', true, 7738, true, 'East', 'Under Construction', 'Ultra Luxury', 95);

-- Update existing localities with more data
UPDATE localities SET 
  amenities = '{"schools": [{"name": "Delhi Public School", "distance": "2 km"}, {"name": "GD Goenka School", "distance": "4 km"}, {"name": "Ryan International", "distance": "5 km"}], "hospitals": [{"name": "Fortis Hospital", "distance": "8 km"}, {"name": "Medanta Hospital", "distance": "10 km"}], "shopping": [{"name": "Omaxe City Centre", "distance": "3 km"}, {"name": "MGF Mall", "distance": "5 km"}], "transport": [{"name": "Sohna Road", "distance": "1 km"}, {"name": "NH-48", "distance": "3 km"}]}'
WHERE slug = 'sohna';

UPDATE localities SET
  amenities = '{"schools": [{"name": "GD Goenka School", "distance": "2 km"}, {"name": "Suncity School", "distance": "3 km"}], "hospitals": [{"name": "Artemis Hospital", "distance": "5 km"}], "shopping": [{"name": "DLF South Point", "distance": "2 km"}], "transport": [{"name": "Sohna Road", "distance": "0.5 km"}, {"name": "Golf Course Road", "distance": "3 km"}]}'
WHERE slug = 'sector-33-sohna';