/*
# Add Sample Rental and PG Data

Populates the rentals and pg_spaces tables with sample data for demonstration.
Allows nullable owner_id for demo data.
*/

-- Insert Sample Rentals
INSERT INTO rentals (title, description, location, address, property_type, listing_type, bedrooms, bathrooms, area_sqft, furnish_status, monthly_rent, security_deposit, maintenance_charges, available_from, minimum_lease_months, amenities, rules, image_url, owner_name, owner_phone, verified, featured, status) VALUES
('Spacious 3BHK in Sohna Road', 'Well-ventilated 3BHK apartment with modern amenities, located in a prime society with excellent connectivity.', 'Sohna Road, Gurgaon', 'Tower A, Sector 49, Sohna Road', 'apartment', 'rent', 3, 2, 1650, 'furnished', 35000, 70000, 3500, '2024-01-15', 11, ARRAY['AC', 'Geyser', 'Modular Kitchen', 'Wardrobes', 'Chimney', 'RO'], ARRAY['No Pets', 'No Smoking', 'Bachelors Allowed'], 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800', 'Rajesh Kumar', '+91 98765 43210', true, true, 'available'),

('Premium 2BHK with Pool Access', 'Semi-furnished 2BHK with premium fittings and access to clubhouse amenities.', 'Sohna City', 'Sector 33, Sohna', 'apartment', 'rent', 2, 2, 1200, 'semifurnished', 28000, 56000, 2500, '2024-02-01', 11, ARRAY['Swimming Pool', 'Gym', 'Club House', 'Children Play Area', '24/7 Security'], ARRAY['Family Preferred', 'No Bachelor Boys'], 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=800', 'Priya Sharma', '+91 98765 12345', true, false, 'available'),

('Independent House Near Naurangpur', 'Spacious independent house with parking, garden area, and excellent ventilation.', 'Naurangpur, Sohna', 'Near Naurangpur Market, Sohna', 'house', 'rent', 3, 3, 2200, 'unfurnished', 32000, 64000, 0, '2024-01-20', 12, ARRAY['Car Parking', 'Garden', 'Terrace Access', 'Water Storage'], ARRAY['Family Only', 'No Non-Veg Cooking'], 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=800', 'Amit Singh', '+91 99888 77665', false, false, 'available'),

('Studio Apartment for Professionals', 'Fully furnished studio apartment ideal for working professionals.', 'Sector 5, Sohna', 'Near IT Park, Sector 5', 'studio', 'rent', NULL, 1, 450, 'fullyfurnished', 12000, 24000, 1000, '2024-01-10', 11, ARRAY['AC', 'Bed', 'Wardrobe', 'TV', 'Fridge', 'RO', 'Geyser'], ARRAY['Bachelors Allowed', 'Working Professionals'], 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800', 'Suresh Verma', '+91 98765 11223', true, true, 'available'),

('4BHK Villa with Private Garden', 'Luxury villa with private garden, modern interiors, and covered parking.', 'Sohna Hills', 'Sohna Hills Township, Sohna', 'villa', 'rent', 4, 4, 3500, 'furnished', 75000, 150000, 5000, '2024-02-15', 24, ARRAY['Private Garden', 'Covered Parking', 'AC All Rooms', 'Modular Kitchen', 'Home Theatre', 'Servant Room'], ARRAY['Family Only', 'No Pets'], 'https://images.pexels.com/photos/2089698/pexels-photo-2089698.jpeg?auto=compress&cs=tinysrgb&w=800', 'Manish Aggarwal', '+91 99999 88888', true, true, 'available');

-- Insert Sample PG Spaces
INSERT INTO pg_spaces (title, description, location, address, pg_type, room_types, starting_price, price_includes, meals_included, amenities, rules, image_url, manager_name, manager_phone, verified, featured, rating, total_beds, available_beds, status) VALUES
('Comfort Stay Boys PG', 'Clean and well-maintained PG for boys with homely food and comfortable rooms.', 'Sohna Road', 'Near Sector 49 Metro, Sohna Road', 'boys', ARRAY['single', 'double', 'triple'], 8500, ARRAY['rent', 'meals', 'wifi', 'cleaning', 'laundry'], true, ARRAY['WiFi', 'AC', 'Attached Washroom', 'TV Room', 'Rooftop Access', 'RO Water', '24/7 Security', 'Power Backup'], ARRAY['No Guests After 10 PM', 'No Smoking/Drinking'], 'https://images.pexels.com/photos/2756485/pexels-photo-2756485.jpeg?auto=compress&cs=tinysrgb&w=800', 'Rajeev Malhotra', '+91 98765 44332', true, true, 4.5, 45, 12, 'available'),

('Ladies Paradise PG', 'Safe and comfortable PG for working women with excellent security.', 'Sector 33, Sohna', 'Near Market, Sector 33', 'girls', ARRAY['single', 'double'], 10000, ARRAY['rent', 'meals', 'wifi', 'cleaning'], true, ARRAY['WiFi', 'AC', 'Attached Washroom', 'Kitchen Access', 'Ladies Security', 'CCTV'], ARRAY['No Male Visitors', 'No Late Night Entry'], 'https://images.pexels.com/photos/271648/pexels-photo-271648.jpeg?auto=compress&cs=tinysrgb&w=800', 'Sunita Aggarwal', '+91 88776 66554', true, true, 4.8, 30, 8, 'available'),

('Urban Co-Living Space', 'Modern co-living space for young professionals with premium amenities and community events.', 'Sohna City', 'Tower B, Sohna City', 'co-living', ARRAY['private room', 'shared studio', 'double occupancy'], 15000, ARRAY['rent', 'meals', 'wifi', 'cleaning', 'gym access', 'laundry', 'events'], true, ARRAY['High-Speed WiFi', 'AC', 'Smart TV', 'Gym', 'Co-Working Space', 'Lounge', 'Rooftop Cafe', 'Laundry Service'], ARRAY['No Smoking', 'Community Guidelines'], 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800', 'Arjun Khanna', '+91 77665 55443', true, true, 4.6, 50, 15, 'available'),

('Budget Boys Hostel', 'Affordable accommodation for students and working professionals.', 'Naurangpur', 'Near Market, Naurangpur', 'boys', ARRAY['double', 'triple', 'four'], 5500, ARRAY['rent', 'meals', 'wifi'], true, ARRAY['WiFi', 'Common TV', 'Water Cooler', 'Attached Bathroom'], ARRAY['No Drinking', 'No Guests'], 'https://images.pexels.com/photos/2756485/pexels-photo-2756485.jpeg?auto=compress&cs=tinysrgb&w=800', 'Dinesh Sharma', '+91 99887 76655', false, false, 3.8, 60, 25, 'available');
